# Generated by Django 4.1.2 on 2022-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_casoprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True, verbose_name='Creado por')),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50, null=True, verbose_name='Actualizado por')),
                ('numero', models.IntegerField(default=0)),
                ('accion', models.TextField(max_length=250)),
                ('resultado_esperado', models.TextField(blank=True, max_length=250, null=True)),
                ('precondicion', models.TextField(blank=True, max_length=250, null=True)),
                ('postcondicion', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('numero',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='casoprueba',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='casoprueba',
            constraint=models.UniqueConstraint(fields=('codigo', 'proyecto'), name='caso_prueba_codigo_proyecto_unique'),
        ),
    ]
