# Generated by Django 4.1.2 on 2022-10-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_paso_alter_casoprueba_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='caso_prueba',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='proyecto.casoprueba'),
            preserve_default=False,
        ),
    ]
