# Generated by Django 4.1.2 on 2022-11-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_remove_paso_caso_prueba_casoprueba_pasos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True, verbose_name='Creado por')),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50, null=True, verbose_name='Actualizado por')),
                ('nombre', models.TextField(max_length=80)),
                ('decripcion', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.DeleteModel(
            name='Paso',
        ),
    ]
