# Generated by Django 4.1.2 on 2022-11-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_cicloprueba_delete_paso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cicloprueba',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
