# Generated by Django 4.1.2 on 2022-11-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_rename_decripcion_cicloprueba_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloprueba',
            name='proyecto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_prueba', to='proyecto.proyecto'),
            preserve_default=False,
        ),
    ]
