# Generated by Django 4.1.2 on 2022-11-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_cicloprueba_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True, verbose_name='Creado por')),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50, null=True, verbose_name='Actualizado por')),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('L', 'Bloqueda'), ('A', 'Aprobada'), ('F', 'Fallo')], default='B', max_length=1)),
                ('comentario', models.TextField(blank=True, max_length=250, null=True)),
                ('evidencia', models.ImageField(upload_to='evidencia/%Y/%m/%d/')),
                ('caso_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_ejecutadas', to='proyecto.casoprueba')),
                ('ciclo_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_ejecutadas', to='proyecto.cicloprueba')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
