# Generated by Django 4.1.2 on 2022-11-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_ejecucionprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoprueba',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('L', 'Bloqueada'), ('A', 'Aprobada'), ('F', 'Fallo')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='ejecucionprueba',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('L', 'Bloqueada'), ('A', 'Aprobada'), ('F', 'Fallo')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='ejecucionprueba',
            name='evidencia',
            field=models.ImageField(null=True, upload_to='evidencia/%Y/%m/%d/'),
        ),
    ]
