# Generated by Django 4.1.2 on 2022-11-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_alter_casoprueba_estado_alter_ejecucionprueba_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionprueba',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencia/%Y/%m/%d/'),
        ),
    ]
