# Generated by Django 4.1.2 on 2022-10-30 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True, verbose_name='Creado por')),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50, null=True, verbose_name='Actualizado por')),
                ('activo', models.BooleanField(default=False)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('force_password', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['correo_electronico'],
            },
        ),
        migrations.CreateModel(
            name='Funcionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('formulario', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=100)),
                ('modulo', models.CharField(choices=[('A', 'Angular'), ('S', 'Siaaf')], default='A', max_length=1)),
                ('mostrar', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=250)),
                ('orden', models.IntegerField()),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionalidades', to='seguridad.funcionalidad')),
            ],
            options={
                'ordering': ('nombre',),
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True, verbose_name='Creado por')),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50, null=True, verbose_name='Actualizado por')),
                ('asunto', models.TextField()),
                ('envio_email', models.DateField(null=True)),
                ('mensaje', models.TextField()),
                ('url', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(null=True)),
                ('session_key', models.CharField(max_length=40, verbose_name='session key')),
                ('user_agent', models.TextField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('ip_address_all', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session activity',
                'verbose_name_plural': 'Session activity',
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('V', 'Visto'), ('L', 'Leído')], default='P', max_length=1)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', '-notificacion__created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuncionalidadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionalidadesGroups', to='seguridad.funcionalidad', verbose_name='Funcionalidad')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionalidadesGroups', to='auth.group', verbose_name='Group')),
            ],
            options={
                'ordering': ('group',),
            },
        ),
    ]
