# Generated by Django 4.1.2 on 2022-11-13 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('path', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionalidadgroup',
            name='funcionalidad',
        ),
        migrations.RemoveField(
            model_name='funcionalidadgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='notificacionusuario',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='notificacionusuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Funcionalidad',
        ),
        migrations.DeleteModel(
            name='FuncionalidadGroup',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='NotificacionUsuario',
        ),
    ]
