# Generated by Django 4.1.2 on 2022-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_logactivity_remove_funcionalidadgroup_funcionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactivity',
            name='content_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logactivity',
            name='method',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='logactivity',
            name='navegador',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logactivity',
            name='referer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='logactivity',
            name='sistema',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
