# Generated by Django 4.1.2 on 2022-11-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_alter_logactivity_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logactivity',
            old_name='date_at',
            new_name='date',
        ),
    ]
