# Generated by Django 4.1.2 on 2022-11-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_logactivity_is_ajax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logactivity',
            old_name='navegador',
            new_name='browser',
        ),
        migrations.RenameField(
            model_name='logactivity',
            old_name='sistema',
            new_name='system',
        ),
    ]
